[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "edge-runtime"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
base = { path = "../base" }
clap = "4.0.29"
env_logger = "0.10.0"
log = { workspace = true }
tokio.workspace = true

