import XlsxTemplate from "https://esm.sh/xlsx-template@1.4.3";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { join } from "https://deno.land/std@0.188.0/path/mod.ts";
import { writeFileSync } from "https://deno.land/std@0.177.0/node/fs.ts";

console.log("XLSX-Template worker started...");

function genReport(data: Uint8Array, nameReport: string) {
  // Create a template
  const template = new XlsxTemplate(data);
  // Replacements take place on first sheet
  const sheetNumber = 1;
  // Set up some placeholder values matching the placeholders in the template
  const values = {
    extractDate: new Date(),
    dates: [
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
    ],
    people: [
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
    ],
  };
  // Perform substitution
  template.substitute(sheetNumber, values);
  // Get binary data
  const report = template.generate();
  // console.log(report);
  writeFileSync(
    join(Deno.cwd(), "api", "xlsx-template", "reports", nameReport),
    report,
    "binary"
  );
}

serve(
  async (_req: Request) => {
    // Load an XLSX file into memory
    const data = await Deno.readFile(
      join(Deno.cwd(), "api", "xlsx-template", "templates", "template1.xlsx")
    );

    const nameReport = "report1.xlsx";
    genReport(data, nameReport);

    return new Response(JSON.stringify({ hello: "XLSX Template" }), {
      headers: { "Content-Type": "application/json", Connection: "keep-alive" },
    });
  },
  { port: 9005 }
);
