import XlsxTemplate from "https://esm.sh/xlsx-template@1.4.3";
import { join } from "https://deno.land/std@0.188.0/path/mod.ts";
import { writeFileSync } from "https://deno.land/std@0.177.0/node/fs.ts";

function genReport(data: Uint8Array, nameReport: string) {
  // Create a template
  const template = new XlsxTemplate(data);
  // Replacements take place on first sheet
  const sheetNumber = 1;
  // Set up some placeholder values matching the placeholders in the template
  const values = {
    extractDate: new Date(),
    /*
      dates: [
        new Date("2023-06-01"),
        new Date("2023-06-02"),
        new Date("2023-06-03"),
      ],
      people: [
        { name: "John Smith", age: 20 },
        { name: "Bob Johnson", age: 22 },
      ],
      */
    dates: [
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
      new Date("2023-06-01"),
      new Date("2023-06-02"),
      new Date("2023-06-03"),
    ],
    people: [
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
      { name: "John Smith", age: 20 },
      { name: "Bob Johnson", age: 22 },
    ],
  };
  // Perform substitution
  template.substitute(sheetNumber, values);
  // Get binary data
  const report = template.generate();
  // console.log(report);
  writeFileSync(
    join(Deno.cwd(), "api", "xlsx-template", "reports", nameReport),
    report,
    "binary"
  );
}

export { genReport };
